Added user management page
danielk0k/its-frontend-manager pull request #5
Opened 2024-02-24 14:35 UTC by thennant

Added user management page together with mockData and mockInstitution files.

2024-02-24 15:56 UTC, danielk0k commented
Hi @thennant maybe you could try using a component library (https://ui.shadcn.com/docs/components/data-table)? I think it helps with code maintainability and easier to add more feature to the table in the future

2024-02-25 13:22 UTC, thennant commented
search bar is a bit too low, promote and delete buttons don't work

2024-02-26 01:32 UTC, danielk0k approved these changes

2024-02-26 02:07 UTC, danielk0k requested changes

2024-02-28 01:09 UTC, danielk0k approved these changes

2024-02-28 01:10 UTC, merged